#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# List EKS clusters
#
# Usage: cluster list clusters
set -euo pipefail

if [[ $# -ne 0 ]]; then
  echo "ERROR: This command takes no arguments" >&2
  echo "Usage: cluster list clusters" >&2
  exit 1
fi

eksctl get clusters
