#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2025-2026 Kaptain contributors (Fred Cooke)
#
# List Kubernetes nodes
#
# Usage: cluster list nodes
set -euo pipefail

if [[ $# -ne 0 ]]; then
  echo "ERROR: This command takes no arguments" >&2
  echo "Usage: cluster list nodes" >&2
  exit 1
fi

kubectl get nodes
